# Generated by Django 5.1.3 on 2024-11-21 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('host_db_drive', models.PositiveIntegerField()),
                ('host_endpoint', models.CharField(max_length=50)),
                ('host_db_name', models.CharField(max_length=50)),
                ('host_username', models.CharField(max_length=50)),
                ('host_password', models.CharField(max_length=150)),
                ('host_port', models.PositiveIntegerField()),
                ('host_active', models.BooleanField(default=True)),
                ('data_create', models.DateTimeField(auto_now_add=True)),
                ('data_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SQL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('sql', models.TextField()),
                ('result', models.JSONField(blank=True, null=True)),
                ('data_create', models.DateTimeField(auto_now_add=True)),
                ('data_update', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.host')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('data_json', models.TextField(default='{}')),
                ('type_chart', models.IntegerField(default=1)),
                ('emphasis', models.BooleanField(default=False)),
                ('data_create', models.DateTimeField(auto_now_add=True)),
                ('data_update', models.DateTimeField(auto_now=True)),
                ('sql', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sql')),
            ],
        ),
    ]
