# Generated by Django 5.1.3 on 2024-11-14 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_sreem', models.CharField(choices=[('light', 'Claro'), ('dark', 'Escuro')], default='light', max_length=5)),
                ('config_download', models.BooleanField(default=False)),
                ('config_maintenance', models.BooleanField(default=False)),
                ('config_navigation', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('data_cron', models.CharField(max_length=100)),
                ('data_json', models.JSONField()),
                ('data_create', models.DateTimeField(auto_now_add=True)),
                ('data_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('host_endpoint', models.CharField(max_length=50)),
                ('host_username', models.CharField(max_length=50)),
                ('host_password', models.CharField(max_length=150)),
                ('host_port', models.PositiveIntegerField()),
                ('data_create', models.DateTimeField(auto_now_add=True)),
                ('data_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SQL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('sql', models.TextField()),
                ('data_create', models.DateTimeField(auto_now_add=True)),
                ('data_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('type_chart', models.CharField(choices=[('bar', 'Coluna'), ('line', 'Linha'), ('pie', 'Pizza')], max_length=5)),
                ('order', models.PositiveIntegerField()),
                ('data_create', models.DateTimeField(auto_now_add=True)),
                ('data_update', models.DateTimeField(auto_now=True)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.data')),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.host'),
        ),
        migrations.AddField(
            model_name='data',
            name='sql',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sql'),
        ),
    ]
