# Generated by Django 5.1.3 on 2024-11-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='type_chart',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sql',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Chart',
        ),
    ]
