# Generated by Django 5.1.3 on 2024-11-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_data_type_chart_alter_sql_name_delete_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='emphasis',
            field=models.BooleanField(default=False),
        ),
    ]
